baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Lucy Thomas"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"
    
Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - enable:false
      identifier: .
      name: .
      title: .
      url: 
      weight: 1
    - enable:false
      identifier: .
      name: .
      title: .
      description: 
      url: 
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Lucy's Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    brandName: "Lucy Thomas" # Brand name for the brand | default is the title variable
    disableSearch: false
    menus:
      disableAbout: false
      disableDescription: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Lucy"
    subtitle: "I'm a 4th year student at McMaster University"
    content: "Aspiring Speech Language Pathologist looking for employment in her gap year"
    image: /images/hero.svg
    button:
      enable: false
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://example.com
        - icon: fab fa-twitter
          url: https://example.com
      customIcons:
        - icon: /fav.png
          url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I am interested in persuing a career as Speech Langauge Pathologist or a Communication Disorders Assistant. 
      
      In my free time I enjoy reading, and watching Gilmore Girls. 
      
      Description of Portfolio;
      
      Target Audience- graduate school programs and future employers
      
      The goal of the portfolio- To provide resources for Speech Language Pathologists and Linguists, and to make educational materials for linguistics classes.
      
      Programs I want to include - Programs in PRAAT and Swirl modules for linguistics courses
    
       
  #Description of the Portfolio 
  Description:
    enable: true
    title: "Description of Portfolio "
    content: |-
      Target Audience is graduate school programs
      The goal of this portfolio is to showcase programming in PRAAT and make Swirl modules for linguistics courses
      I would also like to compile useful packages for SLPs and Linguists
      
  # Experience
  experience:
    enable: false
    # title: "Custom Name"
    items:
      - job: "Research Assisitant"
        company: "Reading Lab"
        companyUrl: "https://kupermanreadlab.humanities.mcmaster.ca/kupermanreadlab/"
        date: "September 2022 - present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://example.com"
        content: "I am currently working as a Research Assistant in the Reading Lab"

      - job: "SLP Volunteer"
        company: "Lear Communication"
        companyUrl: "https://example.com"
        date: "Sep 2020 - Dec 2021"
        featuredLink:
          enable: true
          url: "https://example.com"
        info:
          enable: true
          content: .
        content: |
          
      - job: "Editor in Chief"
        company: "SciWise"
        companyUrl: "https://example.com"
        date: "Jan 2020 - Aug 2020"
        info:
          enable: false
        featuredLink:
          enable: true
          url: "https://example.com"
        content: |-
         
  # Education
  education:
    enable: false
    # title: "Custom Name"
    index: false
    items:
      - title: "B.A in Cognitive Science of Language"
        school:
          name: "McMaster University"
          url: "https://example.org"
        date: "2019 - 2023"
        GPA: "TBD!"
        content: |-

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: http://127.0.0.1:4541/


  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Speech Calculations App
        content: An app which calculates speech rate, number of syllables, and Mean Length Utterance
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://lucyrthomas.shinyapps.io/speechcalculationsapp/
        badges:
          - "R"
          - "Shiny Apps"  
       
      - title: Swirl Course
        content: This Swirl Course teaches you about Mean Length of Utterance (MLU)
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "R"
          - "Swirl"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: lucyrthomas8@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/lucyrthomas
      linkedin: https://www.linkedin.com/in/lucy-thomas4/
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false
